### ISSUE TITLE
Gap between character sequences after upgrading to v4

### ISSUE THREAD

**Issue by iixixv** [tonsky/FiraCode#1050]
v3 is working as expected using Kitty terminal, I've tested different font that has ligatures support and works properly as well.
![image](https://user-images.githubusercontent.com/20151138/82662491-3d5aa200-9c2e-11ea-8453-0bbacddd5735.png)

After upgrading to v4 it shows as following :
![image](https://user-images.githubusercontent.com/20151138/82664273-a5f74e00-9c31-11ea-9a87-735e74b8d86d.png)

OS : Arch Linux
Terminal Emulator : Kitty 0.17.4

Thanks in advance!

**Comment by tonsky** [comment]
In v3, each ligature was a single glyph, thus always rendered perfectly. In v4 arrows are now constructed of multiple little pieces. That allows them to combine in various combinations in a way that was impossible in previous versions. 

But is has a downside, too. Many terminals and editors round up letter widths to whole pixels. E.g. in font metrics a letter is supposed to take 9.841 px, but in practice terminals allocate 10 px for it. That makes rendering easy for them, but that also means, depending on font size, you might have a gap or overlap up to the 1 pixel, unfortunately.  Fira Code includes slight overshoot to compensate for small gaps, but I can’t make it too large, otherwise bumps appear at the edges of the glyphs. I’m afraid there’s no way around those.

**Comment by wopian** [comment]
> otherwise bumps appear at the edges of the glyphs. I’m afraid there’s no way around those.

Like this? (Font size 13 in VSCode)

![image](https://user-images.githubusercontent.com/3440094/82702000-0e155680-9c69-11ea-8995-6be745755be9.png)

**Comment by tonsky** [comment]
@wopian I’m afraid so

**Comment by iixixv** [comment]
@tonsky That's unfortunate, but gaps only appear between first two characters in a sequence using `kitty`
![image](https://user-images.githubusercontent.com/20151138/82905768-8e3b0500-9f64-11ea-87be-1ef6522c0a5a.png)

**Comment by iixixv** [comment]
On linux I could tell it worked though on a [build](https://github.com/iixixv/st) of `st` with the ligatures patch.

![image](https://user-images.githubusercontent.com/20151138/82905500-40260180-9f64-11ea-828e-70551b5fe021.png)
