### ISSUE TITLE
Dotted zero stylistic set gone in v4?

### ISSUE THREAD

**Issue by jaromir-benes** [tonsky/FiraCode#1058]
Hi - just want to make sure I understand correctly... Is the dotted zero stylistic set gone in v4 (see the screenshot)? Or is it perhaps just a glitch in macOS? I would hate to see dotted zeros go (and would really want you to fall for them one day, too, so that they become the default:)). Many thanks for all your amazing work...

Best
Jaromir
<img width="258" alt="image" src="https://user-images.githubusercontent.com/25515306/82989768-79f61700-9ffb-11ea-8ee0-d3b4d2b3fbdb.png">

**Comment by tonsky** [comment]
No, it is still exposed under standard name `zero`:

<img width="260" alt="Screenshot 2020-05-27 at 14 22 06" src="https://user-images.githubusercontent.com/285292/83018383-7f685700-a025-11ea-8ad8-9751cbec9ce9.png">

Stylistic set was a duplication of that under `ss19` name, mainly because Sublime Text didn’t support `zero`. But ST didn’t support `ss` > 10, so it served no purpose and is now gone.

**Comment by tonsky** [comment]
And don’t mind the name (Slashed Zero), it is default name that I have no control over. The idea is that it changes the look of zero, in Fira Code case slashed is default, but with that enabled it’ll be dotted.
