### ISSUE TITLE
Character is moved almost out of sight

### ISSUE THREAD

**Issue by Vampire** [tonsky/FiraCode#1167]
I don't know whether you can actually do something to improve or fix this, but I'm reporting it in case you can.
Removing the range-operator ligature is not what I want, as it anyway just happens in combination with a different bug.

If you have FiraCode as monospace font in your browser and look at https://gebish.org/manual/3.4.1/#indexes-and-ranges, the Groovy example with the `assert`s.
That page currently uses prettify for highlighting which is a bad choice as it does not actually support Groovy.
Because of that the code is parsed as something else, probably Java and the result is
`<span class="lit">0.</span><span class="pun">.</span><span class="lit">1</span>` instead of
`<span class="lit">0</span><span class="pun">..</span><span class="lit">1</span>`.

For FiraCode there are still two dots following each other so it is moving the first dot to the right.
But in this case this results in the first dot being almost out of sight, just the left-most pixel remains visible:
![grafik](https://user-images.githubusercontent.com/325196/101781696-6f632100-3af8-11eb-9681-62ed0c545bfc.png)

**Comment by tonsky** [comment]
Firefox? I think that’s the part where they don’t respect HTML tags split, try to apply ligature to the whole text but then paint parts of it with different colors. This is what I am getting:

<img width="157" alt="Screenshot 2020-12-11 at 12 42 35" src="https://user-images.githubusercontent.com/285292/101899860-c88d8c00-3bae-11eb-8aa3-bbc7d96ba720.png">

The top one is `<span>1.</span><span>.</span>`
The bottom one I changed to be `<span>1..</span>`

I don’t think I can do much here. The most that can be done is reporting this to Firefox itself.

This is what Chrome is doing:

<img width="131" alt="Screenshot 2020-12-11 at 12 44 48" src="https://user-images.githubusercontent.com/285292/101900071-291cc900-3baf-11eb-8583-df0ae9d1ec6a.png">

because dots are in different tags, it doesn’t try to make them into a ligature. Which is closer to the intention, I think: if you put things in diffrent tags, you probably don’t want them to ligate.

**Comment by Vampire** [comment]
Yes Firefox.
I agree that it is probably more an error of Firefox to not respect the tag split.

But Chrome is a totally different story actually.
Maybe I'm too dumb, but I don't get any ligatures at all.
I modified the DOM to have the correct `<span>1</span><span>..</span>` but the ligature was not applied at all.

**Comment by tonsky** [comment]
> `<span>1</span><span>..</span>`

It should’ve. There are some font settings that can turn them off, or you might forgot to apply Fira Code.

**Comment by Vampire** [comment]
Im just becmoing more and more confused. :-/
I did apply Fira Code, I selected it in the settings as monospaced font and the devloper tools say Fira Code is the rendered font and it is the same Book of Geb page where the ligatures are displayed erroneously with Firefox.

On the other hand, if go to https://fonts.google.com/specimen/Fira+Code?preview.text=0..&preview.text_type=custom as there the ligatures in Chrome work with Firefox, there copy the element that is displaying the entered text to end up with the dots split in separate tags they are not joined together, even if I change the tags to be `span`.

**Comment by Vampire** [comment]
Chrome also does not behave "correctly".
I now have on fonts.google.com also a `..` ligature shown in Chrome where `0.` is in the first span and `.` in the second.

**Comment by Vampire** [comment]
![grafik](https://user-images.githubusercontent.com/325196/101919527-f97bba00-3bca-11eb-80cb-d4fe87f6358d.png)
![grafik](https://user-images.githubusercontent.com/325196/101919544-fda7d780-3bca-11eb-85b4-c3415bee2df7.png)

**Comment by tonsky** [comment]
I think you also need to apply different styles (e.g. color)

**Comment by Vampire** [comment]
But anyway it is probably not your topic why in Chrome the ligatures are not shown for the book of geb any why both do ligate where they maybe shouldn't.

**Comment by Vampire** [comment]
You mean like that?
![grafik](https://user-images.githubusercontent.com/325196/101920233-dac9f300-3bcb-11eb-992d-e9b697a39a2f.png)

That makes it even more confusing actually:
![grafik](https://user-images.githubusercontent.com/325196/101920271-e5848800-3bcb-11eb-814f-6f592f2d4eee.png)

**Comment by tonsky** [comment]
Now I am confused too :)))

**Comment by Vampire** [comment]
It is also the same in Firefox and Chrome
Anyway, I at least now reported the Firefox issue which is the most important as it makes characters almost not noticable: https://bugzilla.mozilla.org/show_bug.cgi?id=1681972
