### ISSUE TITLE
Bold‘s font name is wrong

### ISSUE THREAD

**Issue by DustinWin** [tonsky/FiraCode#1172]
For example, the font name of "Light" is "Fira Code Light". The font name of "Bold" is "Fira Code". However, the font name of "regular" is "Fira Code". This makes it impossible to choose "Fira Code Bold" when choosing a font.
![image](https://user-images.githubusercontent.com/45238096/102856236-0d43dd80-4461-11eb-8349-1788249c08f6.png)

**Comment by kenmcd** [comment]
You are looking at the Style Groups in the Windows font previewer.
The **Fira Code** style group includes Regular, Italic, Bold, and Bold Italic.  
Those are selected with the Bold and Italic buttons in the applications.
The **Fira Code Light** is another style group.  
If the application lists the fonts by Typographic Family, rather than Style Groups, then you would see the individual fonts listed.
This is normal behavior.

**Comment by DustinWin** [comment]
> You are looking at the Style Groups in the Windows font previewer.
> The **Fira Code** style group includes Regular, Italic, Bold, and Bold Italic.
> Those are selected with the Bold and Italic buttons in the applications.
> The **Fira Code Light** is another style group.
> If the application lists the fonts by Typographic Family, rather than Style Groups, then you would see the individual fonts listed.
> This is normal behavior.

OK, thank you!

**Comment by kenmcd** [comment]
Look at Arial, Times New Roman, etc. - you will see the same thing in the Windows font previewer.

**Comment by DustinWin** [comment]
> Look at Arial, Times New Roman, etc. - you will see the same thing in the Windows font previewer.

Yeah, I found it. And "FZLanTingYuanGBK Bold", the font name shows "FZLanTingYuanGBK", not "FZLanTingYuanGBK Bold".
