### ISSUE TITLE
Shorthand attributes in svelte have italic brackets

### ISSUE THREAD

**Issue by guilhermefront** [tonsky/FiraCode#1263]
In svelte there's a shorthand for attributes that have the same name of the value

example:
```
const src = 'assets/image.png';

<img {src} />
```

The problem is: with this syntax the brackets change to italic, like this:
![image](https://user-images.githubusercontent.com/49620737/125179524-1e69f700-e1c5-11eb-8ad7-8231d25137d3.png)

**Comment by RubenVerg** [comment]
That's something your theme is doing, not the font. Try switching to eg Monokai or the default ones, it's because the `{}` in shorthand use a different token type (the same one as an attribute, so the attr name in eg `title={title}` should look like those curly brackets) and whatever theme you're using (looks like some Uno Due Tre one) styles attribute keys in italics

**Comment by guilhermefront** [comment]
Thanks for your answer!
