### ISSUE TITLE
Bug in FiraCode-Bold.ttf name

### ISSUE THREAD

**Issue by MrV-777** [tonsky/FiraCode#1565]
Hi,

Found a bug in FiraCode-Bold.ttf name that looks from long time nobody fixed :). 
The issue with font name in container, all details in screenshot attached. 
If load FiraCode-Bold.ttf and after FiraCode-Regular.ttf in memory programmatically in Windows OS Regular Font appears as Bold because is not unique named, some OOP doesn't have ability to specify names, so the solution use Bold or Regular can't use both, in Web is no matter works well, not in Software.

![Fira_bug](https://github.com/tonsky/FiraCode/assets/81026979/2f9fe583-8546-4bc8-8a26-1c5d1ac761c9)

**Comment by tonsky** [comment]
I think that’s how most fonts work? Same name, different styles? That’s what allows programs to group them together

**Comment by kenmcd** [comment]
This is normal.
The Windows Font Viewer shows the style group as the "Font Name".
And since Regular and Bold are both in the same `Fira Code` style group - it shows the same thing.
The full font name is in the title bar above that.

If a font has Regular, Italic, Bold, and Bold Italic - all four would show the same thing.
Below is Arial as an example.
Note how all four show Arial as the Font Name.
But the title bar shows the correct full font name.

![2023-12-20_10-23-41](https://github.com/tonsky/FiraCode/assets/844920/11c116e9-585a-4507-96e0-697d153111a1)
