### ISSUE TITLE
italic support

### ISSUE THREAD

**Issue by vanhp** [tonsky/FiraCode#172]
Please add italic support.

**Comment by tonsky** [comment]
It’s just too much to do, and I’m not a font designer. If Fira Mono adds it, I would probably add it for ligatures, but not for the whole font

**Comment by lencioni** [comment]
Here is the issue to follow if you are interested in this: https://github.com/mozilla/Fira/issues/38

**Comment by wolverian** [comment]
At least http://mozilla.github.io/Fira/ shows italics, even though mozilla/Fira#38 is still open.

**Comment by tonsky** [comment]
They are for Sans version only, not Mono

**Comment by wolverian** [comment]
Doh, thanks! 🐱

**Comment by UnaiM** [comment]
Just in case someone hasn’t seen this yet, there is a Fira fork with italics for Mono: [https://github.com/mozilla/Fira/issues/38#issuecomment-136099951](url)

**Comment by rschr** [comment]
Is "won't fix" still the undisputable resolution here? I like what I see, but without proper italics Fira Code is not usable for me in a modern UI (unless, perhaps, I'd want to modify each and every language's syntax highlighting definition so that it will refrain from using italics, which would still be a poor workaround).

**Comment by tonsky** [comment]
It is
