### ISSUE TITLE
What about publishing as webfont to cdn?

### ISSUE THREAD

**Issue by zxqfox** [tonsky/FiraCode#18]
It would be great to use the most actual version of this on web sites right from CDN.

What you think about it?

**Comment by tonsky** [comment]
Are there any free ones?

**Comment by zxqfox** [comment]
@tonsky Some well-known: https://cdnjs.com/, http://www.jsdelivr.com/, or even github.io (https://pages.github.com/) :smirk_cat:

**Comment by okonomiyaki3000** [comment]
Also try to get hosted on https://www.google.com/fonts 
I don't think I would use this font for writing code but I would use it for displaying code. So it would be great to have it conveniently loadable in this way.

**Comment by WorldMaker** [comment]
:+1: This would be great to have on Google Fonts, at the very least.

**Comment by tonsky** [comment]
A link to remember https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Comment by tomByrer** [comment]
I can add it to jsDelivr for you, including automated updating (since you use [releases](https://github.com/tonsky/FiraCode/releases).  I think it would be easiest to have your GitHub folder like this:
```
/dist
  firacode.css (should be minified)
  /ttf
    (files)
  /woff
    (files)
  /woff2
    (files)
```
Don't bother with EOT or SVG fonts anymore please.  [WOFF2 covers over half of browser usage](http://caniuse.com/#feat=woff2), so that should try to load first.
Also helpful: https://github.com/google/woff2

**Comment by tonsky** [comment]
Thanks! I’ll try to get webfonts for next release

**Comment by tomByrer** [comment]
Welcome.
Did more research; seems [EOT is needed only if you need to support IE 6-8](http://caniuse.com/#search=eot)..  [TTF has bad support in IE](http://caniuse.com/#feat=ttf) oddly enough, & really is only needed in some old (2/3? of Android <=4.3).  WOFF is supported IE9+ & Android 4.4 (& some 4.x).  So you could get away with just WOFF & WOFF2, since IE8 & old Android is unlikely going to be used by programmers anyhow.

(Some browsers have a bug that tries to d/l all font files, even if not used.  That's why Google Fonts sniffs browser agent, & serves a custom CSS.  jsDelivr can't sniff; sorry.)

**Comment by Jastrzebowski** [comment]
Meanwhile can we use tools like mentioned https://github.com/google/woff2, and self host converted fonts without breaking the OFL terms?

**Comment by simon-matt** [comment]
[rawgit.com](https://rawgit.com/) looks great :smiley: 

Direct URL to latest version:
[https://cdn.rawgit.com/tonsky/FiraCode/master/distr/ttf/FiraCode-Regular.ttf](https://cdn.rawgit.com/tonsky/FiraCode/master/distr/ttf/FiraCode-Regular.ttf)

**Comment by remyabel** [comment]
@simon-matt Not a particularly good idea. See the front page:

> Use a specific tag or commit hash in the URL (not a branch). Files are **cached permanently** based on the URL. Query strings are ignored. 

The URL only makes sense for tagged releases and that would have to be updated manually.

**Comment by stereobooster** [comment]
Distribution as npm package would work for me, like in https://github.com/KyleAMathews/typefaces

**Comment by j-f1** [comment]
**CSS**: https://unpkg.com/firacode/distr/fira_code.css

**Comment by Ir1d** [comment]
Hi, I wonder if there's a plan on adding Fira Code to Google Fonts. Thx!

**Comment by xlanor** [comment]
Given that rawgit is closing down (https://rawgit.com/), would it be possible to publish the latest version to npm (https://www.npmjs.com/package/firacode), such that the README.md would use unpkg in the sample?

**Comment by j-f1** [comment]
Looks like someone else has that package name, but @tonsky could [contact the user and npm](https://www.npmjs.com/policies/disputes) to get access.

**Comment by WorldMaker** [comment]
JsDelivr also supports GitHub CDN like RawGit did, as another option.

**Comment by jam1e** [comment]
This font is now available via Google Fonts: https://fonts.google.com/specimen/Fira+Code?selection.family=Fira+Code
