### ISSUE TITLE
Smalltalk ligatures

### ISSUE THREAD

**Issue by krono** [tonsky/FiraCode#19]
The following sequences might appear in Smalltalk code:

 - [x] `~~` “Not identical”
 - [x] `~=` “Not equal” (as `!=` in other languages)
 - [x] `#[` Start of a literal byte array
 - [ ] `[: ` Start of a block with arugments
 - [ ] `]]]` End of multiple blocks.

Example

```Smalltalk
MyClass>>myMessageWith: aNumber otherThing: anObject

    aNumber ~= anObject ifTrue: [
        anObject ~~ #mySymbol ifFalse: [
            ^ #[ 43 54 26 123 33 45 98 192 158 158]]].
   "consider anObject as a collection"
   ^ anObject inject: aNumber into: [:sum :each | sum + 3 * each]
```

**Comment by tonsky** [comment]
Ok, first three added to v0.4

Optimizing `[:` is not a great idea as it seems that colon belongs to word after it, not to bracket. In other words, `[:` is not a single symbol. It’ll also conflict with Clojure’s vector with keyword: `[:keyword]`

`]]]` is not actually optimizable via ligatures because we don’t know how many of them there’re. Spacing seems great as it is.

**Comment by krono** [comment]
ok. sounds good to me.
Thanks
