### ISSUE TITLE
greater than and less than should use ≤ ≥ 

### ISSUE THREAD

**Issue by llehn** [tonsky/FiraCode#263]
Currently greater than and less than use &leqslant; and &geqslant; 

This is actually uncommon. HTML's "commonly used" symbols are &leq; (&leq vs &leqslant) Latex uses /leq. The germans even have a DIN standard where they set ≤ ≥ as standard.

But the most important point is: it is visually more distinguishable from < and > signs.

So I suggest using &leq; instead of &leqslant;

**Comment by llehn** [comment]
Actually this is a cultural difference. I spent half of my life in russia, there we used ⩾ all the time :D But here it's uncommon. A fork would probably be a solution, anybody with a mac?

**Comment by igorsantos07** [comment]
Here in Brazil I'm not sure I've ever seen ≤ ≥ until I stumbled upon then in the IT world.
I'm also not sure if these would be easier to distinguish than ⩽ ⩾. I guess that's more related to your font size or whatnot, but I'm not the font-specialist around here :smile:

**Comment by Idyllei** [comment]
I agree that ≤ and ≥ are easier to distinguish, but I feel ⩽ and ⩾ are easier to look at and follow the style of the rest of the ligatures in the font pack.

**Comment by tonsky** [comment]
Let’s use random numbers generator to decide https://twitter.com/firacode/status/777129225774043136 :)

**Comment by ivanatpr** [comment]
How about a culturally-neutral approach with ligatures for >= and <= that simply streamline the original two characters by vertically aligning them and reducing the space between them, like the current ligature for ":=" does?

That would have the added benefit, in my mind, of having the ligatures more closely resembles the original two characters. With both ⩾ and ≥ it seems like there's enough difference between what I typed and what actually ends up on the screen that clarity ends up impaired rather than increased.

**Comment by Entroper** [comment]
Any plans to do anything with this?  Would love to have ligatures in my code, but not if I'm more likely to make silly errors.  These are honestly harder to distinguish.
