### ISSUE TITLE
Ligature Request: =~ and !~

### ISSUE THREAD

**Issue by sos4nt** [tonsky/FiraCode#293]
In Ruby and Perl there is `=~` to match a pattern (regex) and `!~` to not match a pattern:

``` ruby
"foo" =~ /o/
"foo" !~ /o/
```

It would be nice to have ligatures for both of these operators.

I propose the _almost equals sign_ and the _not almost equals sign_:

``` ruby
"foo" ≈ /o/
"foo" ≉ /o/
```

(Adjusted for width, of course)

Regarding #167 (`export PATH=~/.local/bin:$PATH`) – I thinks it's safe to "activate" these ligatures only when there is whitespace around them (which is the idiomatic way to write the operators in both, Ruby and Perl): `X =~ Y` would trigger, `X=~Y` would not.

**Comment by joffrey-bion** [comment]
These ligatures seem pretty invasive to me. They completely change the perception of the actual operator which has a specific meaning in these languages. I think readers would get confused when seeing them, but that's just my personal opinion.

**Comment by Drenmi** [comment]
Another option, which would preserve the distinct parts of the original operators:

```
foo ≅ /o/
foo ≇ /o/
```

**Comment by Crissov** [comment]
Where the tilde is used for the home directory it is almost always immediately followed by a slash. This could have been used to suppress the ligature and thus handle #167.

@Drenmi's suggestion of an elongated or centered U+2245 ≅ for `=~` seems sound, but for `!~` I'd rather expect something like U+2249 ≉ instead of U+2247 ≇, U+2246 ≆ or  U+2244 ≄. There does not seem to be a precomposed character in Unicode of a single tilde with diagonal strike-through.

**Comment by tonsky** [comment]
> but there usually is a space before the leading slash

I can’t rely on this sort of heuristic. It won’t work too often and users will end up with some magic replacement that sometimes works but sometimes does not. That increases confusion, and Fira Code goal always was to decrease confusion.

**Comment by daurnimator** [comment]
Sometimes `~` is an unary operator; or used as a home directory.
e.g. I wouldn't want this to render differently:
```
PATH=~/.local/bin:"$PATH"
```

Nor this lua 5.3 code (where `~` is unary bitwise NOT):
```lua
foo=~bar
```

**Comment by tonsky** [comment]
Added to ss07
