### ISSUE TITLE
<= and =< look the same. Hard to find syntax error

### ISSUE THREAD

**Issue by scottgrayson** [tonsky/FiraCode#355]
I just wrote a syntax error in javascript accidentally using `=<` for comparison. I couldn't tell it was wrong until i copy pasted into a chat room, because fira code produces the same symbol with both `<=` and `=<`

Is there a use for this? Can `=<` be made to look different or be ignored?

**Comment by tonsky** [comment]
One of them should be made optional, yes

**Comment by thasmo** [comment]
Can't `=<` be a bit like `/=`'s ligature?

**Comment by j-f1** [comment]
In addition, many help pages say `x=<the value of x>`, which is ligatured to `x⩽the value of x>`.

**Comment by willpower232** [comment]
this is particularly an issue if the symbol is part of a string in something like PHP. the ligature will be present in both combinations but an error is not detectable until runtime.

**Comment by danielyli** [comment]
What's the status of this request?

**Comment by tonsky** [comment]
pending

**Comment by danielyli** [comment]
The syntax key=\<value\> is very frequently seen in documentation, whereas the =< syntax for "less than or equals" is used in only two languages, Prolog and Erlang, neither of which is commonly used.

In light of this, I'm curious why this still justifies the =< ligature when @tonsky has used the same argument to overrule inclusion of `/\` and `\/` ligatures (a good decision, I would add):

> `\/` and `/\` are hard to squeese in because they would conflict with escape sequences a lot

https://github.com/tonsky/FiraCode/issues/333#issuecomment-267568194

Is it simply because it was an early decision? https://github.com/tonsky/FiraCode/commit/4af8a24ede7de7020d671f794eb5cd30c94e42da
