### ISSUE TITLE
!== is rendered in different ways depending on context

### ISSUE THREAD

**Issue by RReverser** [tonsky/FiraCode#403]
For the following sample:

```javascript
/*
if (typeof vm.parentCtrl.item[c].pnx.addata.stitle !== 'undefined') {  }
if (typeof vm.parentCtrl.item[c].pnx.addata.date !== 'undefined') {  }
if (typeof vm.parentCtrl.item[c].pnx.addata.cop !== 'undefined') {  }
*/
```

I see same `!==` sequence rendered in three different ways in VS Code with Fira Code 1.204, whereas I would expect first representation to be used in each of them:

<img width="656" alt="screen shot 2017-04-03 at 16 15 40" src="https://cloud.githubusercontent.com/assets/557590/24616368/d717ee52-1888-11e7-8965-4ff74e8d3126.png">

Strangely, issue doesn't appear when I try to remove pieces of code in the condition or uncomment this piece of code, but still can't understand the reason why it occurs.

**Comment by sainaen** [comment]
Hi, Ingvar! :)

This is a third report of the weird ligatures in VS Code (see #397 and #372), so at this point I bet it's something wrong with their renderer again and not the font itself. But it may be already fixed in more recent builds of VS Code with the [commit](https://github.com/Microsoft/vscode/commit/235566665cd8e85238662d57947a956d27a5c19d) that supposedly fixes both previously reported issues. I don't know if they have nightly builds for you to try though.

**Comment by RReverser** [comment]
Interesting, thanks. I'll try to check out later builds.
