### ISSUE TITLE
Shrink === and !==

### ISSUE THREAD

**Issue by AnthonyJacob** [tonsky/FiraCode#418]
Recently I have looked into Monoid ligatures for `===` and `!==` and they both looked much more pleasant (probably because they are smaller, more compact). It would be nice if FiraCode had similar image for them.

**Comment by wopian** [comment]
Comparison of the two at 16px:

![](https://i.imgur.com/BLSOpQd.png)

**Comment by dospunk** [comment]
Wouldn't this interfere with the monospace nature of the font?

**Comment by dhouck** [comment]
There’re fully monospace fonts where all characters are the same width, and there are modular-width fonts where everything is a multiple of the base width but not necessarily the multiple you expect. This wouldn’t exactly be modular-width because the individual characters of the ligature would be smaller than the base font width, but it would have the same effect.

The problem with modular-space fonts is that different rendering engines don’t handle them all quite the same way. If you’re using Vim in a terminal, then Vim might have a different idea of what column you’re on than the terminal logical character position does, which might be different than what the terminal renders. Even if all your software works together, if you need to work with other people who care about maximum line length or anything, using something like that could confuse the issue.

Not everybody wants a monospace font for coding, but most people do and this gets rid of some of those benefits. There should probably be a font with coding ligatures for those who don’t want to code monospace, but Fira Code is not it and I don’t think this suggestion would work well in a monospace font.

**Comment by AnthonyJacob** [comment]
Nope, there will be just more empty space. 

⁣Odesláno z BlueMail ​

2. 8. 2017 4:16 PM, 4:16 PM, dospunk <notifications@github.com> napsal/a:

**Comment by tonsky** [comment]
Thanks for the suggestion. I think I’m fine with it looks currently. Having `=` and `==` be as much disctinct as reasonably possible is very important, so naturally I want `==` to be as long as possible. `===` is a different case, but I don’t want people to see extra space character when there’s nothing but the empty space from the glyph
