### ISSUE TITLE
*** Does not work on Atom using the markdown-language package

### ISSUE THREAD

**Issue by dospunk** [tonsky/FiraCode#472]
The *** ligature does not show when using the `markdown-language` package on Atom

OS: macOS Sierra (64 bit)
Atom: 1.18.0 x64
Using the version of FiraCode provided by the `fonts` Atom package

**Comment by dhouck** [comment]
Does it work if you set the document type to plain text? (Obviously that isn’t ideal, but it’s useful for debugging)

If not, then you probably have ligatures set up incorrectly somehow.

If so, then it’s because the `markdown-language` package doesn’t read that as a single token. There is no way for Fira Code to fix that; it’s being asked to render `*` three times and doesn’t know that it’s surrounded by other asterisks.

**Comment by dospunk** [comment]
In plain text it works. It also works in there's only one `***` on the line, but if you write, for example, `***Bold and italicized text***` the `***`s display as a `**` ligature with one `*` next to it. I can provide screenshots in a bit if that would be helpful.

**Comment by tonsky** [comment]
Please report those directly to Atom or syntax plugin you’re using. This is not a font issue https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont

**Comment by dospunk** [comment]
Will do, thank you!

**Comment by dhouck** [comment]
In that case it’s the Markdown tokenizer, deciding that `***Bold and italicized text***` should be tokenized as `**` `*` `Bold and italicized text` `**` `*` (which is incorrect tokenization anyway, since the closing version should be in reverse order). There is nothing Fira Code can do about it, because it doesn’t know that the `**` is immediately followed by a third `*`.

It looks like if you uninstall language-markdown (or uncheck the “Disable language-gfm” box in its settings), then set your document to use Github Markdown format, it will render the `***` ligature correctly.
