### ISSUE TITLE
Ligature request: [:]

### ISSUE THREAD

**Issue by stoneburner** [tonsky/FiraCode#486]
In Swift, you specify an empty dictionary with `[:]`, which could be a nice looking ligature

```swift
var dict = [:]
```

**Comment by j-f1** [comment]
It also means to make a copy of a list in Python:

```py
my_list = [1, 2, 3]
my_other_list = my_list[:]
my_list.append(4)
my_list # => [1, 2, 3, 4]
my_other_list # => [1, 2, 3]
```

**Comment by tonsky** [comment]
Well I went down that path with `[]` ligature (drawn as complete square). Although some people find it beautiful (including myself), most though it was a glitch in a font. The problem was that it made empty lists look different from other lists, although semantically they were the same.

The only thing I could (and should) fix about this, I guess, is to vertically center `:` to brackets. I’ll do that in the next version, thanks for the idea!

**Comment by j-f1** [comment]
@tonsky Python also supports `[1:]` and `[:3]`-style subscripts. Could you add some sort of ligature for those?

**Comment by tonsky** [comment]
Yeah, I know. I already adjust colon position around numbers and capital letters
