### ISSUE TITLE
Mix of Bold and Not Bold is not Monospace anymore

### ISSUE THREAD

**Issue by MalcolmMielle** [tonsky/FiraCode#552]
Some editor highlight variable by making them bold ([Jucii++](https://github.com/cppit/jucipp)). Having both Bold and not bold at the same time makes the language not monopace anymore.

**Comment by MalcolmMielle** [comment]
Monoisome suffers from the same problem.

**Comment by jeruane** [comment]
I've run into the same issue.

It's particularly annoying in Intellij with the "darcula" color scheme. This scheme defaults to **bold**-ing matched braces, which shifts the text ever so slightly due to this bug.

If anyone else has this problem with the "darcula" color scheme in Intellij, the quick fix is to turn off **bold** text when doing matched brace highlighting in Intellij. This setting can be found here (as of `2019.1`):
`Settings -> Editor -> Color Scheme -> General -> Code -> Matched Brace`

**Comment by tonsky** [comment]
What OS are you on? Windows/mac/linux? Also what font size, font weight, and are you using TTF or OTF files?

**Comment by jeruane** [comment]
I'm on macOS Version: `10.14.6 (18G84)`
Font: `Fira Code Retina (1.207)`
Font size: `12`
Using TTF files

Please let me know if you need any more details

**Comment by tonsky** [comment]
Can you please try files from this commit? https://github.com/tonsky/FiraCode/tree/b32369cb03ad3c0fe43fd30fd19427169e9592dc/distr/ttf

I moved both ascender and descender down a bit, which fixed bold/having different height for me at least in TextEdit.app.

Let me know how if that fixed it for you too. Thanks!
