### ISSUE TITLE
Old style nums variant prevents lot of ligatures

### ISSUE THREAD

**Issue by paradoxxxzero** [tonsky/FiraCode#561]
## Problem

Some characters like `=` (`equal`) have an identical onum variant (`equal.tosf`). This breaks the ligatures since there are none with `equal.tosf`.

## Exemple

 - Normal:
![screenshot from 2018-03-01 16-09-29](https://user-images.githubusercontent.com/271144/36852025-0bc0ce66-1d6b-11e8-9def-49e28b7d45ef.png)

 - With ligatures (default):
![screenshot from 2018-03-01 16-09-37](https://user-images.githubusercontent.com/271144/36852041-1649b96a-1d6b-11e8-8c5d-262fe2bde431.png)

 - With oldstyle nums:
![screenshot from 2018-03-01 16-09-43](https://user-images.githubusercontent.com/271144/36852062-2225c044-1d6b-11e8-9f41-4537588055f7.png)

 - With both:
![screenshot from 2018-03-01 16-09-47](https://user-images.githubusercontent.com/271144/36852074-289bc522-1d6b-11e8-90dd-338ec9f80ced.png)

## Suggestion:
Remove the `.tsof` variant for characters that doesn't change with the onum feature to restore default ligatures.

Thanks

**Comment by tonsky** [comment]
Makes sense, but still leaves lots of characters that do change. May I ask what’s your use-case? Why are you turning on both old-style numerals and ligatures?

**Comment by paradoxxxzero** [comment]
Because I like coding with old-style nums (for some reason it helps me read long numbers) and I like this font ligatures!

**Comment by paradoxxxzero** [comment]
FYI I removed (with fontforge I don't have access to glyphs) all `.tsof` variants except numbers (which seem to be the only ones varying) and everything is working fine except the `multiply` (1x1) and the `uc` (1:1) ligatures that operate on regular numbers and not on the old style. (It still is a lot better)

**Comment by camsteffen** [comment]
Would someone be so kind to explain this change for curious simpletons like myself?

**Comment by j-f1** [comment]
This change means that you’ll be able to use old-style numbers along with ligatures that appear directly next to numbers. Here’s a screenshot showing the difference between normal and old-style numbers:

<img height="35" alt="Screen Shot 2019-09-13 at 16 18 48" src="https://user-images.githubusercontent.com/25517624/64892351-2ba61100-d642-11e9-9a17-47d53c4d51f0.png">

**Comment by tonsky** [comment]
@camsteffen 

Ligatures are pattern based. E.g. you want to replace `->` with an arrow. The code for that would be:

```
sub hyphen greater by hyphen_greater.liga;
```

So if your program sees `hyphen` glyph followed by `greater` glyph it would replace both with a single `hyphen_greater.liga` which contains a double-width arrow in case of Fira Code.

Old-style numbers are implemented the same way:

```
sub zero by zero.onum;
sub one by one.onum;
```

The problem is that it used to replace not only numbers but some symbols like -, +, <, >, % and so on. If onum substitution happens first ligatures won’t work because character is not different:

```
hyphen greater -> hyphen.onum greater.onum -> ??? (does not match <hyphen> <greater>)
```

This change removes substitutions for everything except the numbers, so both old-style numbers and ligatures can work at the same time.
