### ISSUE TITLE
The greater than and less than font don't look right in VS Code

### ISSUE THREAD

**Issue by zhaoyi0113** [tonsky/FiraCode#583]
I followed this instruction to setup FiraCode in vs code: https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions.
But the font doesn't look right. See below screenshot:

![image](https://user-images.githubusercontent.com/3355579/38492777-61862030-3c33-11e8-8599-ca2a6e3abb9f.png)

You can see that the greater than and less than don't match the example shown in the FIraCode readme. Below is what I expected.

![image](https://user-images.githubusercontent.com/3355579/38492812-7de8b5d0-3c33-11e8-8c84-0ab9615c6201.png)

My vs code version is `1.21.1`

**Comment by tonsky** [comment]
This is a different, probably fallback font. Either you haven’t installed Fira Code (you have to download the archive and move it to Fonts folder, see https://github.com/tonsky/FiraCode/wiki#installing-font) or you config is wrong. 

What OS do you use?
Can you post your config?

**Comment by zhaoyi0113** [comment]
I am using Mac OS. I just did a installation by these commands:

```
brew tap caskroom/fonts
brew cask install font-fira-code
```
And below is the new screenshot, you can see that it is still different for the greater than and less than.

![image](https://user-images.githubusercontent.com/3355579/38494482-694196a0-3c39-11e8-8b2f-0dfefa34fd3b.png)


Below is my settings:

```
"editor.fontLigatures": true,
    "editor.fontFamily": "'Fira Code'",
```

I also tried remove the single quote for fontFamily but still the same issue.

**Comment by tonsky** [comment]
Seems like the right font now. You might be experiencing this https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont . What happens if you set syntax to plaintext? Do ligatures appear?

**Comment by zhaoyi0113** [comment]
This is the screenshot for plaintext:

![image](https://user-images.githubusercontent.com/3355579/38494759-6c82232e-3c3a-11e8-8f32-9861ca5a243e.png)

**Comment by tonsky** [comment]
Okay, looks like something isn’t working :) I have no idea what, but couple of steps that might help:

- Check your font in other app. E.g. Apple Terminal.app supports ligatures. Change the font there and see if they work
- Check VS Code config again, restart, etc
- Install font by directly downloading OTF files from this repo (link to zip in Releases)

**Comment by tonsky** [comment]
Well, I’m afraid I’m out of ideas. Try this?

```
"editor.fontFamily": "FiraCode-Regular",
```

**Comment by zhaoyi0113** [comment]
I already tried that. Anyway thanks for your help.

**Comment by gusbemacbe** [comment]
@tonsky and @zhaoyi0113 

I had this problem and I found the solution for this problem! It was a bug of macOS Sierra and High Sierra, because the cache is old. You needed to remove the cache to restore FontBook that VSCode recognised the font.

1. Close VSCode 

2. Run via terminal:
```
tsutil databases -removeUser
atsutil server -shutdown
atsutil server -ping 
```

Here is the result:

![screen shot 2018-05-04 at 13 12 13](https://user-images.githubusercontent.com/2257024/39638545-eea541d6-4f9c-11e8-9701-80f29512760e.png)

![screen shot 2018-05-04 at 13 13 51](https://user-images.githubusercontent.com/2257024/39638570-0603bc2c-4f9d-11e8-9d81-9b85d26993fc.png)

As for the terminal and turn the ligatures on, only you can use the extension [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) and overwrite the original VSCode CSS.

```css
.monaco-workbench .panel.integrated-terminal 
{
    font-variant-ligatures: contextual;
}
```

You can discuss it: https://github.com/be5invis/vscode-custom-css/issues/39

Or maybe a VSCode-hakcing guru @mohouyizme can help you.

**Comment by tonsky** [comment]
Thanks for letting me know!
