### ISSUE TITLE
Array push operator []=

### ISSUE THREAD

**Issue by g105b** [tonsky/FiraCode#637]
I use the array push operator in PHP very often:

```php
$people = [];
$people []= "tonsky";
$people []= "j-f1";
$people []= "Dominionized";
$people []= "herlev";
```

I feel like a ligature for this operator would help visualise this operator's usage very much so.

Thanks for such an amazing open source project!

**Comment by tonsky** [comment]
interesting, thanks!

**Comment by kmvan** [comment]
I thank shall be ```$people[] = "Jack";```

**Comment by jdreesen** [comment]
@kmvan right, that's how most people write it. 
The example from @g105b is syntactically correct, though.

**Comment by g105b** [comment]
@kmvan @jdreesen I don't know of anyone who writes `$array[] = $pushedElement`.

Neither do I know anyone who does `$string. = "concat";` or `$number+ = 123`.

Operators should always be surrounded by spaces for consistency.

**Comment by jdreesen** [comment]
Well, your argument makes sense, but I've rarely seen anyone using that style, even on the internet.

Even in the [code examples](https://secure.php.net/manual/en/function.array-push.php) in the [PHP docs](https://secure.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying) the square brackets are [aligned at the variable](https://secure.php.net/manual/en/language.types.array.php#language.types.array.examples) instead of the equal sign.

But in the end, it's simply a matter of taste, of course :)
So it certainly wouldn't hurt to add a ligature for it.

**Comment by j-f1** [comment]
Additionally, GitHub doesn’t style the `[]=` operator as one symbol:

<img width="187" alt="screen shot 2018-08-23 at 4 05 43 pm" src="https://user-images.githubusercontent.com/25517624/44549187-55fef680-a6ee-11e8-8e24-4110fcf1b26b.png">

This means that even if a ligature is added, it will only be visible if the `[]` and the `=` are the same style.

**Comment by g105b** [comment]
@kmvan you're mixing two operators. The first, `[]=` is the array push operator. The second, `=` is simply the assignment operator, in your case being used on an array.

**Comment by steffanredneck** [comment]
@g105b I was about to say the same thing. `$array []= $item` makes so much sense to me and my team... it's weird to think that so many guides use a space between the operator characters... just look at the concatenation operator and keep it consistent.

btw there needs to be no argue here, because if you don't like the correct syntax nothing is forcing you to use it and the ligiture will not come into action.

**Comment by kmvan** [comment]
@g105b I know that. But like this:
```php
$a = [];
$a []= 'a';
$a [0]= 'a'; // equal above, do you think it is good alignment?
```

**Comment by g105b** [comment]
```php
$a = []; // this is the assignment operator, assigning an empty array to $a.
$a []= 'a'; // this is the push operator, pushing 'a' into $a.
$a[0] = 'a' // this is the assignment operator, assigning 'a' to index 0 of $a.
```

Not sure where the `$a [0]= 'a'` style comes into this. To me, this makes no sense, as you're adding an unnecessary space between the array and its index, and using the assignment operator with a space only to the right of the operator.

**Comment by kstep** [comment]
There's no such thing as a "push operator" in PHP. Even in official docs, no mention of such operator appears, and everywhere the `$arr[] = "a";` version is used, which is just an assignment to the end of array element (syntax sugar for `$arr[len($arr)] = "a";`). I see your version for the first time in my life (and I've programmed in PHP for more than 5 years).

**Comment by g105b** [comment]
I rarely see this syntax either, @kstep. I'm not arguing that it is common, but just that I would find it super useful.

**Comment by kmvan** [comment]
> @kmvan @jdreesen I don't know of anyone who writes `$array[] = $pushedElement`, it's just weird that way. I have certainly seen it written like that online though, but the issue I raised won't affect people who like to decorate their operators in such unusual style.
> 
> Neither do I know anyone who does `$string. = "concat";` or `$number+ = 123`.
> 
> Operators should always be surrounded by spaces for consistency.
> 
> ```
> $something .= $value;
> $something += $value;
> $something *= $value;
> $something []= $value;
> ```

`.=` is aleardy exist.

**Comment by rikkimax** [comment]
In D ``Expression '[' ']'`` is a slice operator very commonly used for assignments. However it is uncommon to have a space between the expression and the open square brackets. Although legal, the space should occur before the equals sign instead.

Which means this isn't a PHP specific request.

**Comment by g105b** [comment]
Thanks everyone for your contributions.
