### ISSUE TITLE
C# verbatim string literal double double-quotation

### ISSUE THREAD

**Issue by star47raven** [tonsky/FiraCode#721]
![image](https://user-images.githubusercontent.com/8971900/53274620-249ecc00-370d-11e9-8ac7-4e86e186feb8.png)

Those double quotation marks in the literal are supposed to output a single ( " ), I'm not sure if two quotemarks together are used in any other __special__ scenario beside this, so it'll be nice to have this on the table.

**Comment by j-f1** [comment]
They’re also used for empty strings: `""`

**Comment by star47raven** [comment]
> They’re also used for empty strings: `""`

Yea, kinda makes me feel like there's no good glyph which suits both, but meantime I consider it a good thing to have a glyph for empty strings.
My thoughts tho, dunno about other devs.

**Comment by tonsky** [comment]
I guess it’s C#-specific, in other languages it is used for empty strings or as a part of """. Since Fira Code is supposed to be language-agnostic, I can’t add it at the moment.

Another concern is that it’s impossible to distinguish between beginning and end of the string in a font. E.g. in `@"""Hi"""` we should highlight two last quotes in the beginning but two first ones at the end.
