### ISSUE TITLE
Deligaturizing "=<"

### ISSUE THREAD

**Issue by MasonMcGill** [tonsky/FiraCode#751]
I discovered that "=<" is converted to "≤" while writing [docopt](http://docopt.org/)-style CLI descriptions (`--key=<value>` turns into `--key≤value>`). Maybe this is unintentional?

Fantastic work on this project, by the way. I've found it very helpful and enjoyable!

**Comment by tonsky** [comment]
It’s intentional (I think Erlang uses =< instead of <=), but you raise a valid concern. Maybe it should be removed. Thanks!

**Comment by boyedarat** [comment]
Maybe there should be a "FiraCode Terminal" font specially for use in the terminal?
Like what Iosevka does. I believe =< should stay, not removed.

**Comment by justme-1968** [comment]
just noticed that in the mac os terminal =< is not contracted into a ligature. don't know if the reason is the fiera code version (old) or if it is a feature of terminal.app.

**Comment by miniBill** [comment]
I'm confused, hadn't the `=<` ligature already been removed?
https://github.com/tonsky/FiraCode/commit/b96ceee8b651ef9f05f4971799d54591c4c9d7ed

**Comment by mheiber** [comment]
I installed FiraCode today directly from the repo and am not seeing a ligature for `=<`. It's too bad, I was hoping for one because `=<` is indeed "less than or equal to" in Erlang, as @tonsky [pointed out](https://erlang.org/doc/reference_manual/expressions.html#term-comparisons).

This does seem like an unfortunate conflict with docopt.

**Comment by tonsky** [comment]
Yes it was removed. It might come back as a part of Erlang stylistic set, follow #34 for that
