### ISSUE TITLE
Erlang's /= and =/=

### ISSUE THREAD

**Issue by dmitriid** [tonsky/FiraCode#8]
Two more additions to inequalities would be nice: Erlang's inequality operators `/=` and `=/=`

**Comment by tonsky** [comment]
`/=` will conflict with C-like languages (divide and assign). `=/=` could be added

**Comment by turbohz** [comment]
Is this a common issue? I mean the language conflicts.
Because a font per language would prevent that.

How difficult is to make these changes and compile the font? 
I could help, but I don't know where to start.
Any suggestions? Maybe some online tutorial?

**Comment by tonsky** [comment]
Not common, but I remember I discarded some ligature because of that. Probably it was a `/=` :)
Fira Code is language-agnostic. But other fonts can be created based on it, sure. Right now there’s no clean pipeline for building Fira Code from sources (see https://github.com/mozilla/Fira/issues/62 and https://github.com/mozilla/Fira/issues/75). I just open OTF, and ligatures, package it back. I used RoboFont for that, but Fira designers are apparently using Glyphs 2 preview

**Comment by turbohz** [comment]
Thanks, that will do!

**Comment by tonsky** [comment]
Added =/= in 0.2

**Comment by dmitriid** [comment]
You rock!
