### ISSUE TITLE
What's the difference between Fira Code and Fira Code Retina

### ISSUE THREAD

**Issue by JerryGoyal** [tonsky/FiraCode#872]
Seems noob question but I couldn't spot the difference between Fira Code and Fira Code Retina. Is it somehow related to retina display or what? Difference is missing in the Wiki also.

**Comment by BinaryMisfit** [comment]
From my own experience the Retina version is meant to provide better support on Apple Retina displays. I tend to use the non Retina version since I use none Retina displays connected to my MacBook and find it slightly more blurry on non Retina but apart form that can't visually notice a difference between the two versions. However I suspect people that are hyper aware of fonts would notice a difference. I suspect if it's the only type of display you use it will be a better default choice.

**Comment by tonsky** [comment]
Retina is just sliiiightly bolder than Regular. I called it Retina because on Retina fonts seems a bit thinner than on non-retina screens, so it compensates just for that. Traditionally a weight between Regular and Medium is called Book, but I decided, if the font is for 21-st century and for screen use only, we should not use books in the name.

**Comment by taw00** [comment]
Note, Book generally slips in between Light and Regular, not Regular and Medium. Book weight is 350 (Light is 300, Regular is 400, and Medium is 500). I have never seen anything in between Regular and Medium so, sure! Name it Retina. :)
Anyway. Glad the mystery is eliminated. Should be added someplace more prominent though, IMHO.

Thanks. -t
